# Generated by Django 5.2 on 2025-04-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geturlmodel',
            old_name='pro_url',
            new_name='Product_URL',
        ),
    ]
