# Generated by Django 5.2 on 2025-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_storeurldetailsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geturlmodel',
            name='user',
        ),
    ]
