# Generated by Django 5.2 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_geturlmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeurldetailsmodel',
            name='title',
            field=models.TextField(default='No Title'),
            preserve_default=False,
        ),
    ]
