# Generated by Django 5.2 on 2025-04-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_storeurldetailsmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeurldetailsmodel',
            name='product_image',
        ),
        migrations.AddField(
            model_name='storeurldetailsmodel',
            name='reviews',
            field=models.TextField(null=True),
        ),
    ]
