# Generated by Django 5.2 on 2025-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_storeurldetailsmodel_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeurldetailsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
