# Generated by Django 5.2 on 2025-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storeurldetailsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurldetailsmodel',
            name='reviews',
            field=models.JSONField(null=True),
        ),
    ]
