# Generated by Django 5.2 on 2025-04-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_storeurldetailsmodel_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeurldetailsmodel',
            name='reviews',
            field=models.TextField(null=True),
        ),
    ]
