# Generated by Django 5.2 on 2025-04-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_storeurldetailsmodel_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeurldetailsmodel',
            name='sentiment',
            field=models.TextField(null=True),
        ),
    ]
